#Sample GitHub Action File.
name: "Hello World"

on:
  pull_request:
    branches:
      - main
    
jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
      - name: Set environment variable
        run: echo "MY_VARIABLE=${{ SLACKURL }}" >> $GITHUB_ENV
      - name: "Clone Code"
        uses: actions/checkout@v2
      - name: "Run Slack Notification!"
        run: python .github/scripts/merge_slack.py

  